version: '3.7'
services:
  web:
    container_name: ${PROJECT}_web
    image: emgware/react
    volumes:
      - .:.
      - /usr/local/share/.cache/yarn:/usr/local/share/.cache/yarn
    command: yarn start
    environment:
      - PROJECT
    ports:
      - "3000:3000"
    env_file:
      - ./.env.${STAGE}

  cosmos:
    container_name: ${PROJECT}_cosmos
    image: emgware/react
    ports:
      - "5000:5000"
    volumes:
      - .:.
    command: yarn cosmos
    environment:
      - PROJECT

  test:
    container_name: ${PROJECT}_test
    image: emgware/react
    volumes:
      - .:.
    command: yarn test
    environment:
      - PROJECT
